#!/usr/bin/env node

const program = require('commander');
const readstdin = require('readstdin');

const validProperties = {
  'fontFamily': function(item, type){ 
    if(type === 'prop') {
      return 'font-family';
    } else if(type === 'value') {
      return item
    }
  },
  'fontWeight': function(item, type){ 
    if(type === 'prop') {
      return 'font-weight';
    } else if(type === 'value') {
    } 
  },
  'fontSize': function(item, type){ 
    if(type === 'prop') {
      return 'font-size';
    } else if(type === 'value') {
    }
  },
  'textCase': function(item, type){ 
    if(type === 'prop') {
      return 'text-transform';
    } else if(type === 'value') {
    }
  }
}

/**
* format color from {r: 0, g: 0, b: 0} 
* to rgb(0, 0, 0)
*/
function formatColor(ocolor) {
  let result = 'rgb(';
  Object.keys(ocolor).forEach((key, i) => {
    if(i < 3) {
      result += `${ocolor[key] * 255}`;
      if(i < 2) 
        result += ',';
    }
  });
  result += ')';
  return result;
}

let styleTransformers = {
  'TEXT': function(css, item) {
    css += `${item.name} {\n`;
    Object.keys(item.style).forEach((key) => {
      if(validProperties[key]) {
        let prop = validProperties[key](item, 'prop'),
            value = validProperties[key](item, 'value');
        css += `\t${prop}: ${value} !important;\n`;
      }
    });
    css += `\tcolor: ${formatColor(item.fills[0].color)} !important;\n`
    css += '}\n\n';
    return css;
  },
  'VECTOR': function(css, item) {
    // absoluteBoundingBox:
    // { x: -5473, y: 46288, width: 223, height: 47.02142333984375 },
    // constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
    // fills:
    // [ { blendMode: 'NORMAL',
    //     type: 'SOLID',
    //     color:
    //      { r: 0.0470588244497776,
    //        g: 0.20000000298023224,
    //        b: 0.43921568989753723,
    //        a: 1 } } ],
    css += `${item.name} {\n`;
    css += `\twidth: ${item.absoluteBoundingBox.width}px !important;\n`;
    css += `\theight: ${item.absoluteBoundingBox.height}px !important;\n`;
    if(item.fills.length) {
      css += `\tbackground-color: ${formatColor(item.fills[0].color)} !important;\n`
    } else if(item.strokes.length) {
      css += `\tborder: ${item.strokeWeight}px ${item.strokes[0].type} ${formatColor(item.strokes[0].color)};`
    }
    css += '}\n\n';
    return css;
  }
}

let classesList = [];

/**
* append to css variable based 
* on the type of nome, creating the class 
* and styles
*/
function appendCSS(item, css) {
  if(item.type === 'TEXT' || item.type === 'VECTOR') {
    if((item.name.match(/^\./) || item.name.match(/^\#/)) && 
      !classesList.find(elem => elem === item.name)){
      classesList.push(item.name);
      css = styleTransformers[item.type](css, item);
    }
  } else {
    if(item.children) {
      item.children.forEach((subitem) => {
        css = appendCSS(subitem, css); 
      });
    }
  }
  return css;
}

async function run(cmd) {
  let data = null;
  data = await readstdin(); 
  data = JSON.parse(data)['document'];
  if(!data) {
    console.error('no data was piped to the program!');
    return;
  }
  
  let css = '';
  if(data['children']) {
    data['children'].forEach((item) => {
      css = appendCSS(item, css);   
    });
  }else {
    css = appendCSS(data, css);
  }

  console.log('// GENERATED BY FIGMA2CSS START')
  console.log(css);
  console.log('// GENERATED BY FIGMA2CSS END')
};

run();
